---
title: "Simulation Work"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 3
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# Simulations -- Model "Power"/Sensitivity Analysis
Simulating under the model. Incidence curves are generated from a simple SEIR framework for 200 days (betas are adjusted accordingly for shapes).

```{r}
library(tidyverse)
library(COVIDCurve)
library(drjacoby)
#...................... 
# store truth
#......................
fatalitydata <- data.frame(param = paste0("ma", 1:5),
                           truth = c(0.02, 0.03, 0.05, 0.1, 0.2))

#...................... 
# read in simulations
#......................
parammap <- readRDS("~/Documents/GitHub/reestimate_covidIFR_analysis/results/temp_slurm_worker_results/_rslurm_sim_covidcurves/params.RDS") %>% 
  dplyr::mutate(retset = paste0("results_", (1:nrow(.)-1)),
                curvename = rep(c("Exp.Growth", "Interventions", "SecondWave"), 45))

ret.list <- list.files("~/Documents/GitHub/reestimate_covidIFR_analysis/results/temp_slurm_worker_results/_rslurm_sim_covidcurves/", 
                       pattern = "results_[0-9]+.RDS", 
                       full.names = TRUE)

#...................... 
# Subset to specific results
# NB, for memory exhaustion reasons, dont' want to carry around
# too many full MCMC models
#......................
extract_results <- function(path, sero_day = 150, fatalitydata = fatalitydata, CIquant = 0.999) {
  # get fit
  fit <- readRDS(path)[[1]]
  # get relevant seroprevelance at time of fit
  obs_sero <- fit$inputs$IFRmodel$data$obs_serologyrate
  
  # extract IFRs
  ifrs <- COVIDCurve::get_cred_intervals(IFRmodel_inf = fit, 
                                         whichrung = paste0("rung", 1),
                                         what = "IFRparams", 
                                         by_chain = FALSE) 
  
  # # extract infection curve
  # infxncurve <- COVIDCurve::draw_posterior_infxn_points_cubic_splines(IFRmodel_inf = fit,
  #                                                                     CIquant = CIquant,
  #                                                                     by_chain = FALSE)$plotdata
  # 
  
  out <- tibble::tibble(retset = gsub(".RDS", "", basename(path)),
                        obs_sero = obs_sero,
                        IFRs = list(ifrs))
                        #IncidenceCurve = list(infxncurve))
  #saveRDS(out, paste0("~/Documents/GitHub/reestimate_covidIFR_analysis/results/temp_intermed/", out$retset, "_retset.RDS"))
  return(out)
}



# run
#lapply(ret.list, extract_results, sero_day = 150, fatalitydata = fatalitydata, CIquant = 0.99)
retmap <- purrr::map(ret.list, extract_results) %>% 
  dplyr::bind_rows(.) %>% 
  dplyr::inner_join(parammap, ., by = "retset")

```

## IFR and Serological Test Specificity and Sensitivity 

```{r}
#...................... 
# process IFR results
#......................
ifrplot_dat <- retmap %>% 
  dplyr::select(c("curvename", "sens", "spec", "IFRs", "obs_sero")) %>% 
  tidyr::unnest(cols = IFRs) %>% 
  dplyr::mutate(
    spec = factor(spec, levels = c(0.85, 0.90, 0.95), 
                  labels = c("Spec: 0.85", "spec: 0.90", "spec: 0.95")),
    sens = factor(sens, levels = c(0.85, 0.90, 0.95), 
                  labels = c("Sens: 0.85", "sens: 0.90", "sens: 0.95")) 
  ) 

ifrplot_obj <- ifrplot_dat %>% 
  dplyr::filter(param == "ma5") %>% 
  dplyr::left_join(., fatalitydata, by = "param") %>% 
  ggplot() +
  geom_hline(aes(yintercept = truth), color = "#3182bd", linetype = "dashed", size = 1.25, alpha = 0.8) +
  geom_pointrange(aes(x = obs_sero, y = median, 
                      ymin = LCI, ymax = UCI, color = curvename), position = position_dodge(width = 0.5)) + 
  facet_grid(sens ~ spec) + 
  scale_color_viridis_d("Curve Pattern") +
  xlab("") + ylab("IFR Median (95% CI)") +
  theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 14),
        axis.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 12),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 11, angle = 45),
        axis.text.y = element_text(family = "Helvetica", hjust = 0.5, size = 11),
        legend.position = "right",
        legend.title = element_text(family = "Helvetica", face = "bold", vjust = 0.85, size = 12),
        legend.text = element_text(family = "Helvetica", hjust = 0.5, vjust = 0.5, size = 10),
        strip.text = element_text(family = "Helvetica", face = "bold", vjust = 0.85, size = 12),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = "#000000", size = 1))


```
```{r, results='asis', fig.width=8, fig.height=8}
ifrplot_obj
```


<!-- ## IFR and Serological Test Specificity and Sensitivity  -->

<!-- ```{r} -->
<!-- dwnsmpl <- 1e2 -->

<!-- #......................  -->
<!-- # process IFR results -->
<!-- #...................... -->
<!-- inf_infxnplot_dat <- retmap %>%  -->
<!--   dplyr::select(c("curvename", "sens", "spec", "IncidenceCurve", "obs_sero")) %>%  -->
<!--   dplyr::mutate( -->
<!--     obsprev = factor(obs_sero, levels = sort(unique(retmap$obs_sero)),  -->
<!--                      labels = paste0("Prev: ", round(sort(unique(retmap$obs_sero)), 2))), -->
<!--     spec = factor(spec, levels = c(0.85, 0.90, 0.95),  -->
<!--                   labels = c("Spec: 0.85", "spec: 0.90", "spec: 0.95")), -->
<!--     sens = factor(sens, levels = c(0.85, 0.90, 0.95),  -->
<!--                   labels = c("Sens: 0.85", "sens: 0.90", "sens: 0.95")), -->
<!--     sensspec = paste0(sens, "; ", spec), -->
<!--     IncidenceCurve = purrr::map(IncidenceCurve, "plotdata"), -->
<!--     IncidenceCurve = purrr::map(IncidenceCurve, function(x){x[sample(1:nrow(x), size = dwnsmpl), c("time", "infxns", "sim")]}) -->
<!--     ) %>%  -->
<!--   tidyr::unnest(cols = IncidenceCurve) -->

<!-- inf_infxnplot_dat <- retmap %>%  -->
<!--   dplyr::select(c("curvename", "sens", "spec", "curve", "obs_sero")) %>%  -->
<!--   dplyr::mutate( -->
<!--     obsprev = factor(obs_sero, levels = sort(unique(retmap$obs_sero)),  -->
<!--                      labels = paste0("Prev: ", round(sort(unique(retmap$obs_sero)), 2))), -->
<!--     spec = factor(spec, levels = c(0.85, 0.90, 0.95),  -->
<!--                   labels = c("Spec: 0.85", "spec: 0.90", "spec: 0.95")), -->
<!--     sens = factor(sens, levels = c(0.85, 0.90, 0.95),  -->
<!--                   labels = c("Sens: 0.85", "sens: 0.90", "sens: 0.95")), -->
<!--     sensspec = paste0(sens, "; ", spec)) %>%  -->
<!--   tidyr::unnest(cols = curve) -->



<!-- infxnplot_obj <- ggplot() + -->
<!--   geom_line(data = inf_infxnplot_dat, aes(x = time, y = infxns, color = sensspec), size = 0.25, alpha = 0.5) + -->
<!--   geom_line(data = true_infxnplot_dat, aes(x = time, y = infxns), color = "#3182bd", size = 1.1, alpha = 0.9) + -->
<!--   scale_color_viridis_d() + -->
<!--   facet_grid(curvename ~ obsprev) +  -->
<!--   xlab("Time") + ylab("Num. Infxns") + -->
<!--   theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 14), -->
<!--         axis.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 12), -->
<!--         axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 11, angle = 45), -->
<!--         axis.text.y = element_text(family = "Helvetica", hjust = 0.5, size = 11), -->
<!--         strip.text = element_text(family = "Helvetica", face = "bold", vjust = 0.85, size = 12), -->
<!--         panel.background = element_rect(fill = "transparent"), -->
<!--         plot.background = element_rect(fill = "transparent"), -->
<!--         panel.grid = element_blank(), -->
<!--         panel.border = element_blank(), -->
<!--         axis.line = element_line(color = "#000000", size = 1.1), -->
<!--         legend.position = "none") -->

<!-- ``` -->
<!-- ```{r, results = 'asis', fig.width=10, fig.height=8} -->
<!-- infxnplot_obj -->
<!-- ``` -->


























<!-- ```{r} -->
<!-- sessionInfo() -->
<!-- ``` -->
