---
title: "Simulated Data"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 3
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE, eval = TRUE, 
                      results = 'hide', fig.align = 'center')
knitr::opts_knit$set(root.dir = here::here())

```
```{r}
library(tidyverse)
library(drjacoby)
library(COVIDCurve)
library(cowplot)
source("R/extra_plotting_functions.R")
```
```{r}
#...................... 
# read in
#......................
modoutpath <- list.files("results/SimCurves/", pattern = ".RDS", full.names = T)
fit_map <- readRDS("data/param_map/SimCurves/small_param_map.RDS") %>% 
  dplyr::select(c("sim", "curve", "sens", "spec", "fatalitydata", "demog"))


#...................... 
# run function
#......................
plots <- mapply(summarize_plot_simulated_runs, 
                modoutpath = modoutpath, fit_map = list(fit_map))
dir.create("figures/SimCurves/", recursive = T)
mapply(jpgsnapshot, plot = plots, outpath = paste0("figures/SimCurves/", fit_map$sim, ".jpg"), type = "long")
```
```{r, results='asis'}
plots
```
